spring:
  application:
    name: svc-registration
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/registration;AUTO_SERVER=TRUE
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8092

eureka:
  instance:
    hostname: localhost
    non-secure-port: 8761
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
