---
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.h2.Driver
  user: sa
  password: ""
  url: jdbc:h2:mem:sampledb
  validationQuery: "SELECT 1"

logging:
  level: INFO
  loggers:
    dropwizard: DEBUG
