spring:
  application:
    name: svc-eureka
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    non-secure-port: 8761
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
