---
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.h2.Driver
  user: sa
  password: ""
  url: jdbc:h2:mem:sampledb
#  url: jdbc:h2:./data/sampledb
  validationQuery: "SELECT 1"

# Logging settings
logging:
  level: INFO
  loggers:
    com.avg.poc.dropwizard: DEBUG
    org.jdbi: DEBUG
    org.jdbi.v3: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: ./logs/application.log
      archivedLogFilenamePattern: ./logs/application-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC