spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

spring-boot-poc:
  property1: single_property1_yml_PROD
  property2: single_property2_yml_PROD
  properties:
    - property1: array-property-0-property1_yml_PROD
      property2: array-property-0-property2_yml_PROD
    - property1: array-property-1-property1_yml_PROD
      property2: array-property-1-property2_yml_PROD
  list:
    properties: yml_prod1;yml_prod2;yml_prod3
