spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:file:./data/db_test
    driver-class-name: org.h2.Driver
    username: root
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    show-sql: true
##  sql:
#    init:
#      mode: never
#      schema-locations: classpath:/db/h2/schema.sql
#      data-locations: classpath:/db/h2/data.sql
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    user: root
    password: password
    drop-first: true
# url: jdbc:h2:mem:db_test
    url: jdbc:h2:file:./data/db_test
    default-schema: public


spring-boot-poc:
  property1: single_property1_yml_TEST
  property2: single_property2_yml_TEST
  properties:
    - property1: array-property-0-property1_yml_TEST
      property2: array-property-0-property2_yml_TEST
    - property1: array-property-1-property1_yml_TEST
      property2: array-property-1-property2_yml_TEST
  list:
    properties: yml_TEST1;yml_TEST2;yml_TEST3
