spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:./data/db_prod
    driver-class-name: org.h2.Driver
    username: root
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    show-sql: true
    sql:
      init:
        mode: never
        schema-locations: classpath:/db/h2/schema.sql
        data-locations: classpath:/db/h2/data.sql
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    user: root
    password: password
    drop-first: true
    # url: jdbc:h2:mem:db_test
    url: jdbc:h2:file:./data/db_prod
    default-schema: public



spring-boot-poc:
  property1: single_property1_yml_PROD
  property2: single_property2_yml_PROD
  properties:
    - property1: array-property-0-property1_yml_PROD
      property2: array-property-0-property2_yml_PROD
    - property1: array-property-1-property1_yml_PROD
      property2: array-property-1-property2_yml_PROD
  list:
    properties: yml_prod1;yml_prod2;yml_prod3
