spring:
  application:
    name: svc-catalog
  config:
    import: optional:configserver:http://localhost:8888
#  data:
#    mongodb:
#      uri: mongodb://localhost/test
#      database: test

server:
  port: 8093

eureka:
  instance:
    hostname: localhost
    non-secure-port: 8761
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
